//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CommissionIncentiveEntities : DbContext
    {
        public CommissionIncentiveEntities()
            : base("name=CommissionIncentiveEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<lnkCommissionFormula> lnkCommissionFormulas { get; set; }
        public virtual DbSet<lnkCommissionFormulaOrganization> lnkCommissionFormulaOrganizations { get; set; }
        public virtual DbSet<refCommissionFormula> refCommissionFormulas { get; set; }
        public virtual DbSet<refCommissionRateType> refCommissionRateTypes { get; set; }
        public virtual DbSet<refCommissionStructure> refCommissionStructures { get; set; }
        public virtual DbSet<tblAccess> tblAccesses { get; set; }
        public virtual DbSet<tblCommissionBalance> tblCommissionBalances { get; set; }
        public virtual DbSet<tblCommissionJournal> tblCommissionJournals { get; set; }
        public virtual DbSet<tblOrganization> tblOrganizations { get; set; }
        public virtual DbSet<trnCommissionTransaction> trnCommissionTransactions { get; set; }
        public virtual DbSet<trnPayoutTransaction> trnPayoutTransactions { get; set; }
    }
}
