//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class lnkCommissionFormulaOrganization
    {
        public int ID { get; set; }
        public int OrgID { get; set; }
        public int CommissionFormulaID { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreateDT { get; set; }
        public Nullable<System.DateTime> LastUpdateDT { get; set; }
        public int LastAccessID { get; set; }
    }
}
